(()=>{
  const $=(s,r=document)=>r.querySelector(s);
  let social,client,state,started=false,page=0,total=0,searchTimer=0;
  const PAGE=20;
  const ui={search:$('[data-admin-search-v3]'),filter:$('[data-admin-filter-v3]'),button:$('[data-admin-search-btn-v3]'),list:$('[data-admin-users-v3]'),info:$('[data-admin-page-info]'),prev:$('[data-admin-prev]'),next:$('[data-admin-next]')};
  if(!ui.list)return;
  const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(d)};
  const toast=(m,k='info')=>social?.toast?.(m,k);
  const isOwner=()=>state?.access?.role==='owner'&&state?.access?.account_status==='active';
  function friendly(error,fallback='Não foi possível concluir esta ação.'){const msg=String(error?.message||error?.details||'');if(/Owner.*proteg|conta Owner/i.test(msg))return 'A conta Owner é protegida pelo backend.';if(/própria conta/i.test(msg))return 'Você não pode aplicar essa ação à própria conta.';if(/Somente o Owner/i.test(msg))return 'Somente o Owner pode alterar outro administrador.';if(/Duração inválida/i.test(msg))return 'Escolha uma duração válida.';if(/permiss|restrita a administradores/i.test(msg))return 'Você não possui permissão para executar esta ação.';return fallback}
  async function rpc(name,args,button,success){const old=button?.textContent;if(button){button.disabled=true;button.setAttribute('aria-busy','true')}const r=await client.rpc(name,args);if(button){button.disabled=false;button.removeAttribute('aria-busy');if(old)button.textContent=old}if(r.error){toast(friendly(r.error),'error');return null}if(success)toast(success,'success');return r.data}
  const avatar=row=>{const i=document.createElement('img');i.src=row.avatar_url||'assets/avatar.jpg';i.alt='';i.loading='lazy';i.decoding='async';i.onerror=()=>{i.onerror=null;i.src='assets/avatar.jpg'};return i};
  const button=(text,cls,fn)=>{const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;b.addEventListener('click',fn);return b};
  const roleLabel=r=>r.role==='owner'?'Owner':r.role==='admin'?'Administrador':'Usuário';
  const statusLabel=r=>r.account_status==='banned'?'Banido':r.account_status==='suspended'?'Suspenso':'Ativo';
  function moderationText(row){const parts=[];if(row.account_status==='banned')parts.push(row.status_expires_at?`Banido até ${fmt(row.status_expires_at)}`:'Banimento permanente');if(row.account_status==='suspended')parts.push(row.status_expires_at?`Suspenso até ${fmt(row.status_expires_at)}`:'Suspensão permanente');if(row.restriction_id)parts.push(row.restriction_permanent?'Mensagens bloqueadas permanentemente':`Silenciado até ${fmt(row.restriction_expires_at)}`);return parts.length?parts.join(' • '):'Sem restrições ativas'}
  function dialog(){let d=$('[data-admin-user-dialog]');if(d)return d;d=document.createElement('dialog');d.className='admin-user-dialog';d.dataset.adminUserDialog='';d.innerHTML='<form method="dialog" class="admin-user-dialog-card"><div class="admin-user-dialog-head"><div><small>MODERAÇÃO</small><h2 data-dialog-title>Ação administrativa</h2><p data-dialog-copy></p></div><button class="admin-dialog-close" value="cancel" aria-label="Fechar">×</button></div><label>Duração<select data-dialog-duration></select></label><label data-custom-label hidden>Minutos personalizados<input data-dialog-custom type="number" min="1" max="525600" value="120"></label><label>Motivo<textarea data-dialog-reason maxlength="500" rows="3" placeholder="Informe o motivo"></textarea></label><div class="admin-dialog-actions"><button class="social-btn secondary" value="cancel">Cancelar</button><button class="social-btn danger" type="button" data-dialog-confirm>Confirmar</button></div></form>';document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)d.close('cancel')});return d}
  function openAction(row,type){const d=dialog(),title=d.querySelector('[data-dialog-title]'),copy=d.querySelector('[data-dialog-copy]'),select=d.querySelector('[data-dialog-duration]'),customWrap=d.querySelector('[data-custom-label]'),custom=d.querySelector('[data-dialog-custom]'),reason=d.querySelector('[data-dialog-reason]'),confirmBtn=d.querySelector('[data-dialog-confirm]');select.replaceChildren();reason.value='';custom.value='120';customWrap.hidden=true;
    const presets=type==='mute'?[[5,'5 minutos'],[15,'15 minutos'],[30,'30 minutos'],[60,'1 hora'],[360,'6 horas'],[720,'12 horas'],[1440,'24 horas'],[4320,'3 dias'],[10080,'7 dias']]:type==='suspend'?[[60,'1 hora'],[360,'6 horas'],[720,'12 horas'],[1440,'24 horas'],[4320,'3 dias'],[10080,'7 dias']]:[[1440,'24 horas'],[4320,'3 dias'],[10080,'7 dias'],[43200,'30 dias']];
    presets.forEach(([v,l])=>{const o=document.createElement('option');o.value=String(v);o.textContent=l;select.append(o)});[['custom','Personalizado'],['permanent','Permanente']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;select.append(o)});select.onchange=()=>customWrap.hidden=select.value!=='custom';
    title.textContent=type==='mute'?'Silenciar mensagens':type==='suspend'?'Suspender conta':'Banir usuário';copy.textContent=type==='mute'?`${row.display_name||'Usuário'} continuará acessando o site, mas não poderá enviar mensagens durante o período escolhido.`:type==='suspend'?`A conta de ${row.display_name||'usuário'} terá funções limitadas durante o período escolhido.`:`O acesso de ${row.display_name||'usuário'} será bloqueado. Confirme duração e motivo antes de continuar.`;confirmBtn.textContent=type==='mute'?'Aplicar silenciamento':type==='suspend'?'Suspender conta':'Confirmar banimento';confirmBtn.className=type==='mute'?'social-btn primary':'social-btn danger';
    confirmBtn.onclick=async()=>{const permanent=select.value==='permanent',minutes=permanent?null:Number(select.value==='custom'?custom.value:select.value);if(!permanent&&(!Number.isInteger(minutes)||minutes<1||minutes>525600)){toast('Informe uma duração válida.','error');return}const why=reason.value.trim()||null;let data;if(type==='mute')data=await rpc('italo_admin_set_message_block',{target_user_id:row.user_id,duration_minutes:minutes,make_permanent:permanent,reason_text:why,restriction_scope:'chat'},confirmBtn,'Silenciamento aplicado.');else data=await rpc('italo_admin_set_account_status',{target_user_id:row.user_id,new_status:type==='suspend'?'suspended':'banned',duration_minutes:minutes,make_permanent:permanent,reason_text:why},confirmBtn,type==='suspend'?'Conta suspensa.':'Usuário banido.');if(data){d.close('ok');load()}};d.showModal()}
  async function setMember(row,enabled,b){const data=await rpc('italo_admin_set_member',{target_user_id:row.user_id,enabled},b,enabled?'Membro Exclusivo concedido.':'Membro Exclusivo removido.');if(data)load()}
  async function setRole(row,newRole,b){if(!confirm(`${newRole==='admin'?'Tornar':'Remover'} administrador de @${row.username||'usuário'}?`))return;const data=await rpc('italo_admin_set_role',{target_user_id:row.user_id,new_role:newRole},b,'Função administrativa atualizada.');if(data)load()}
  async function clearMute(row,b){if(!confirm(`Liberar as mensagens de ${row.display_name||'este usuário'}?`))return;const data=await rpc('italo_admin_lift_message_block',{target_user_id:row.user_id,restriction_scope:row.restriction_scope||'chat'},b,'Envio de mensagens liberado.');if(data)load()}
  async function reactivate(row,b){const label=row.account_status==='banned'?'Desbanir':'Reativar';if(!confirm(`${label} ${row.display_name||'este usuário'}?`))return;const data=await rpc('italo_admin_set_account_status',{target_user_id:row.user_id,new_status:'active',duration_minutes:null,make_permanent:false,reason_text:null},b,row.account_status==='banned'?'Usuário desbanido.':'Conta reativada.');if(data)load()}
  function render(rows){ui.list.replaceChildren();if(!rows.length){ui.list.innerHTML='<div class="launch-empty">Nenhum usuário encontrado.</div>';return}rows.forEach(row=>{const card=document.createElement('article');card.className='admin-user admin-user-v3';const ident=document.createElement('div');ident.className='admin-user-id';ident.append(avatar(row));const copy=document.createElement('div'),name=document.createElement('strong'),username=document.createElement('small'),email=document.createElement('small');name.textContent=row.display_name||'Jogador';username.textContent=row.username?`@${row.username}`:'Sem username';email.textContent=row.email||'E-mail indisponível';copy.append(name,username,email);ident.append(copy);
      const meta=document.createElement('div');meta.className='admin-user-meta';const role=document.createElement('strong');role.textContent=roleLabel(row);const status=document.createElement('span');status.className=`admin-status ${row.account_status}`;status.textContent=`Status: ${statusLabel(row)}`;const member=document.createElement('span');member.textContent=row.is_member?'★ Membro Exclusivo':'Conta normal';const created=document.createElement('span');created.textContent=`Criado em ${fmt(row.created_at)}`;const seen=document.createElement('span');seen.textContent=`Última atividade: ${fmt(row.last_seen_at)}`;meta.append(role,status,member,created,seen);
      const mod=document.createElement('div');mod.className='admin-user-meta moderation';const ms=document.createElement('strong');ms.textContent=moderationText(row);mod.append(ms);if(row.status_reason){const reason=document.createElement('span');reason.textContent=`Motivo da conta: ${row.status_reason}`;mod.append(reason)}if(row.restriction_reason){const reason=document.createElement('span');reason.textContent=`Motivo do silêncio: ${row.restriction_reason}`;mod.append(reason)}
      const actions=document.createElement('div');actions.className='admin-actions';const self=row.user_id===state.session.user.id,owner=row.role==='owner',targetAdmin=row.role==='admin';const profile=document.createElement('a');profile.className='social-btn secondary';profile.href=row.username?`perfil.html?u=${encodeURIComponent(row.username)}`:'perfil.html';profile.textContent='Perfil';actions.append(profile);actions.append(button(row.is_member?'Remover Membro':'Tornar Membro','social-btn secondary',e=>setMember(row,!row.is_member,e.currentTarget)));
      if(owner){const lock=document.createElement('span');lock.className='admin-owner-protected';lock.textContent='Owner protegido pelo backend';actions.append(lock)}else{if(isOwner()&&!self)actions.append(button(targetAdmin?'Remover ADM':'Tornar ADM','social-btn secondary',e=>setRole(row,targetAdmin?'user':'admin',e.currentTarget)));const manageable=!self&&(isOwner()||!targetAdmin);if(manageable){if(row.restriction_id)actions.append(button('Liberar mensagens','social-btn secondary',e=>clearMute(row,e.currentTarget)));else actions.append(button('Silenciar','social-btn secondary',()=>openAction(row,'mute')));if(row.account_status==='active'){actions.append(button('Suspender','social-btn secondary',()=>openAction(row,'suspend')),button('Banir usuário','social-btn danger',()=>openAction(row,'ban')))}else actions.append(button(row.account_status==='banned'?'Desbanir':'Reativar','social-btn primary',e=>reactivate(row,e.currentTarget)))}}
      card.append(ident,meta,mod,actions);ui.list.append(card)})}
  function updatePager(){const from=total?page*PAGE+1:0,to=Math.min(total,(page+1)*PAGE);if(ui.info)ui.info.textContent=total?`${from}–${to} de ${total} usuários`:'0 usuários';if(ui.prev)ui.prev.disabled=page<=0;if(ui.next)ui.next.disabled=(page+1)*PAGE>=total}
  async function load(){ui.list.innerHTML='<div class="admin-users-skeleton"><i></i><i></i><i></i></div>';const term=(ui.search?.value||'').replace(/\s+/g,' ').trim().slice(0,80),filter=ui.filter?.value||'all';const r=await client.rpc('italo_admin_list_users',{search_text:term||null,filter_name:filter,page_size:PAGE,page_offset:page*PAGE});if(r.error){ui.list.innerHTML='<div class="launch-error">Não foi possível carregar os usuários.</div>';toast(friendly(r.error),'error');return}const rows=r.data||[];total=Number(rows[0]?.total_count||0);if(page>0&&!rows.length&&total){page=Math.max(0,page-1);return load()}render(rows);updatePager()}
  function bind(){ui.button?.addEventListener('click',()=>{page=0;load()});ui.search?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page=0;load()},350)});ui.search?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(searchTimer);page=0;load()}});ui.filter?.addEventListener('change',()=>{page=0;load()});ui.prev?.addEventListener('click',()=>{if(page>0){page--;load()}});ui.next?.addEventListener('click',()=>{if((page+1)*PAGE<total){page++;load()}})}
  function init(s){if(started)return;started=true;social=s;client=s.client;state=s.state;if(!state.session?.user||!['admin','owner'].includes(state.access?.role)||state.access?.account_status!=='active')return;bind();load()}
  document.addEventListener('italo:social-ready',e=>init(e.detail),{once:true});if(window.ITALO_SOCIAL)init(window.ITALO_SOCIAL);
})();