(() => {
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ui={messages:$('[data-chat-messages]'),form:$('[data-chat-form]'),older:$('[data-load-older]'),restriction:$('[data-chat-restriction]'),chatStatus:$('[data-chat-status]'),postForm:$('[data-post-form]'),postCount:$('[data-post-count]'),postFeed:$('[data-post-feed]'),inviteForm:$('[data-invite-form]'),inviteList:$('[data-invite-list]'),ranking:$('[data-ranking-list]'),topics:$('[data-topic-list]'),createTopic:$('[data-create-topic]')};
  let social=null,client=null,session=null,oldest=null,hasOlder=false,messageIds=new Set(),channel=null,loadingOlder=false;
  const pageSize=30;
  const toast=(m,k='info')=>social?.toast?.(m,k);
  const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(d)};
  const fmtDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(d)};
  const escapeId=v=>String(v??'');
  const profileCache=new Map();
  const accessCache=new Map();
  const memberCache=new Map();

  function badgeFor(id){const access=accessCache.get(id);const member=memberCache.get(id);if(access?.role==='owner'){const b=document.createElement('span');b.className='role-badge owner';b.textContent='OWNER';return b;}if(access?.role==='admin'){const b=document.createElement('span');b.className='role-badge admin';b.textContent='ADM';return b;}if(member?.is_member){const b=document.createElement('span');b.className='member-exclusive-badge';b.textContent='★ Membro Exclusivo';return b;}return null;}
  async function hydrateUsers(ids){ids=[...new Set(ids.filter(Boolean).filter(id=>!profileCache.has(id)))];if(!ids.length)return;const [p,a,m]=await Promise.all([client.from('italo_profiles').select('user_id,display_name,username,avatar_url,role_badge,is_channel_member').in('user_id',ids),client.from('italo_account_access').select('user_id,role,account_status').in('user_id',ids),client.from('italo_memberships').select('user_id,is_member').in('user_id',ids)]);(p.data||[]).forEach(x=>profileCache.set(x.user_id,x));(a.data||[]).forEach(x=>accessCache.set(x.user_id,x));(m.data||[]).forEach(x=>memberCache.set(x.user_id,x));}
  function userLink(id,fallback='Jogador'){const p=profileCache.get(id);const a=document.createElement('a');a.className='chat-user-link';a.textContent=p?.display_name||fallback;a.href=p?.username?`perfil.html?u=${encodeURIComponent(p.username)}`:'perfil.html';return a;}
  function avatar(id,url){const p=profileCache.get(id);const a=document.createElement('a');a.href=p?.username?`perfil.html?u=${encodeURIComponent(p.username)}`:'perfil.html';const img=document.createElement('img');img.className='chat-avatar';img.src=p?.avatar_url||url||'assets/avatar.jpg';img.alt='';img.loading='lazy';img.onerror=()=>img.src='assets/avatar.jpg';a.append(img);return a;}
  function canModerate(){return ['admin','owner'].includes(social?.state?.access?.role)&&social?.state?.access?.account_status==='active';}

  function makeMessage(row,{pending=false}={}){const el=document.createElement('article');el.className='chat-message'+(pending?' is-pending':'');if(row.id!=null)el.dataset.messageId=String(row.id);el.append(avatar(row.user_id,row.avatar_url));const main=document.createElement('div');main.className='chat-message-main';const meta=document.createElement('div');meta.className='chat-message-meta';meta.append(userLink(row.user_id,row.display_name));const b=badgeFor(row.user_id);if(b)meta.append(b);const t=document.createElement('time');t.className='chat-time';t.textContent=pending?'enviando…':fmt(row.created_at);meta.append(t);if(canModerate()&&!pending){const actions=document.createElement('span');actions.className='chat-admin-actions';const del=document.createElement('button');del.type='button';del.className='social-btn danger chat-delete';del.textContent='Excluir';del.addEventListener('click',()=>moderateDeleteMessage(row.id,el));actions.append(del);meta.append(actions);}const body=document.createElement('span');body.className='chat-message-text';body.textContent=row.body||'';main.append(meta,body);el.append(main);return el;}
  async function renderMessages(rows,{prepend=false}={}){await hydrateUsers(rows.map(x=>x.user_id));const frag=document.createDocumentFragment();rows.forEach(row=>{if(messageIds.has(String(row.id)))return;messageIds.add(String(row.id));frag.append(makeMessage(row));});if(prepend)ui.messages.prepend(frag);else ui.messages.append(frag);}
  async function loadMessages(reset=true){if(!session?.user)return signedOutChat();if(reset){ui.messages.replaceChildren();messageIds.clear();oldest=null;ui.messages.innerHTML='<div class="community-skeleton"></div><div class="community-skeleton"></div>';}
    let q=client.from('italo_messages').select('id,user_id,display_name,avatar_url,body,created_at,expires_at').order('created_at',{ascending:false}).limit(pageSize+1);if(!reset&&oldest)q=q.lt('created_at',oldest);const r=await q;if(r.error){ui.messages.innerHTML='<div class="community-state">Não foi possível carregar as mensagens.</div>';return;}const data=r.data||[];hasOlder=data.length>pageSize;const page=data.slice(0,pageSize).reverse();if(reset)ui.messages.replaceChildren();await renderMessages(page,{prepend:!reset});if(page.length)oldest=page[0].created_at;ui.older.hidden=!hasOlder;if(reset)requestAnimationFrame(()=>ui.messages.scrollTop=ui.messages.scrollHeight);}
  function signedOutChat(){ui.messages.innerHTML='<div class="community-state">Entre com sua conta para participar da conversa.</div>';ui.older.hidden=true;ui.form?.querySelector('textarea')?.setAttribute('disabled','');}
  async function loadOlder(){if(loadingOlder||!hasOlder)return;loadingOlder=true;ui.older.disabled=true;const before=ui.messages.scrollHeight;await loadMessages(false);requestAnimationFrame(()=>{ui.messages.scrollTop=ui.messages.scrollHeight-before;});ui.older.disabled=false;loadingOlder=false;}
  async function checkRestriction(){if(!session?.user)return;const r=await client.rpc('italo_my_communication_status');const blocked=!!r.data?.blocked;const text=ui.form?.querySelector('textarea');const btn=ui.form?.querySelector('button');if(blocked){const expiry=r.data.permanent?'sem prazo definido':`até ${fmtDate(r.data.expires_at)}`;ui.restriction.textContent=`Você está temporariamente impedido de enviar mensagens ${expiry}.`;ui.restriction.hidden=false;if(text)text.disabled=true;if(btn)btn.disabled=true;}else{ui.restriction.hidden=true;if(text)text.disabled=false;if(btn)btn.disabled=false;}}
  async function sendMessage(e){e.preventDefault();if(!session?.user){toast('Entre com sua conta para conversar.','error');return;}const ta=ui.form.querySelector('textarea');const body=ta.value.trim();if(!body)return;const tempId='temp-'+Date.now();const p=social.state.profile;const optimistic={id:tempId,user_id:session.user.id,display_name:p?.display_name,avatar_url:p?.avatar_url,body,created_at:new Date().toISOString()};await hydrateUsers([session.user.id]);const el=makeMessage(optimistic,{pending:true});el.dataset.tempId=tempId;ui.messages.append(el);ui.messages.scrollTop=ui.messages.scrollHeight;ta.value='';const r=await client.from('italo_messages').insert({user_id:session.user.id,display_name:p?.display_name||'Jogador',avatar_url:p?.avatar_url,body}).select('id,user_id,display_name,avatar_url,body,created_at,expires_at').single();if(r.error){el.remove();ta.value=body;toast(social.errorMessage?.(r.error)||r.error.message,'error');await checkRestriction();return;}messageIds.add(String(r.data.id));el.replaceWith(makeMessage(r.data));}
  async function moderateDeleteMessage(id,el){if(!confirm('Excluir esta mensagem da comunidade?'))return;const r=await client.rpc('italo_admin_delete_message',{message_id:id,reason_text:null});if(r.error){toast(r.error.message,'error');return;}messageIds.delete(String(id));el.remove();toast('Mensagem removida.','success');}

  async function loadPosts(){if(!session?.user){ui.postFeed.innerHTML='<div class="community-state">Entre para ver e publicar na Resenha.</div>';return;}const posts=await client.from('italo_resenha_posts').select('id,user_id,display_name,avatar_url,body,created_at,expires_at').order('created_at',{ascending:false}).limit(20);if(posts.error){ui.postFeed.innerHTML='<div class="community-state">Não foi possível carregar a Resenha.</div>';return;}const rows=posts.data||[];await hydrateUsers(rows.map(x=>x.user_id));const ids=rows.map(x=>x.id);const [likes,comments]=ids.length?await Promise.all([client.from('italo_resenha_likes').select('post_id,user_id').in('post_id',ids),client.from('italo_resenha_comments').select('id,post_id,user_id,display_name,avatar_url,body,created_at').in('post_id',ids).order('created_at',{ascending:true}).limit(200)]):[{data:[]},{data:[]}];await hydrateUsers((comments.data||[]).map(x=>x.user_id));ui.postFeed.replaceChildren();if(!rows.length){ui.postFeed.innerHTML='<div class="community-state">A Resenha está aberta. Publique a primeira conversa.</div>';return;}rows.forEach(post=>ui.postFeed.append(makePost(post,(likes.data||[]).filter(x=>x.post_id===post.id),(comments.data||[]).filter(x=>x.post_id===post.id))));}
  function makePost(post,likes,comments){const el=document.createElement('article');el.className='community-post';const head=document.createElement('div');head.className='post-head';const av=avatar(post.user_id,post.avatar_url);av.firstChild.className='chat-avatar';head.append(av);const hm=document.createElement('div');hm.className='post-head-main';hm.append(userLink(post.user_id,post.display_name));const b=badgeFor(post.user_id);if(b)hm.append(b);const time=document.createElement('small');time.textContent=fmtDate(post.created_at);hm.append(time);head.append(hm);if(canModerate()){const del=document.createElement('button');del.className='social-btn danger chat-delete';del.type='button';del.textContent='Excluir';del.addEventListener('click',()=>moderateDeletePost(post.id,el));head.append(del);}const body=document.createElement('p');body.className='post-body';body.textContent=post.body;const toolbar=document.createElement('div');toolbar.className='post-toolbar';const mine=likes.some(x=>x.user_id===session.user.id);const like=document.createElement('button');like.type='button';like.className='social-btn secondary';like.textContent=`${mine?'♥':'♡'} ${likes.length}`;like.addEventListener('click',async()=>{const r=mine?await client.from('italo_resenha_likes').delete().eq('post_id',post.id).eq('user_id',session.user.id):await client.from('italo_resenha_likes').insert({post_id:post.id,user_id:session.user.id});if(r.error)toast(r.error.message,'error');else loadPosts();});toolbar.append(like);const count=document.createElement('span');count.className='community-note';count.textContent=`${comments.length} comentário${comments.length===1?'':'s'}`;toolbar.append(count);const commentsBox=document.createElement('div');commentsBox.className='post-comments';comments.forEach(c=>{const row=document.createElement('div');row.className='comment-row';row.append(avatar(c.user_id,c.avatar_url).firstChild);const x=document.createElement('div');x.append(userLink(c.user_id,c.display_name));const p=document.createElement('p');p.textContent=c.body;x.append(p);row.append(x);commentsBox.append(row);});const form=document.createElement('form');form.className='comment-form';const input=document.createElement('input');input.maxLength=350;input.placeholder='Comentar…';input.required=true;const send=document.createElement('button');send.className='social-btn secondary';send.type='submit';send.textContent='Enviar';form.append(input,send);form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;const p=social.state.profile;const r=await client.from('italo_resenha_comments').insert({post_id:post.id,user_id:session.user.id,display_name:p.display_name,avatar_url:p.avatar_url,body:text});if(r.error){toast(r.error.message,'error');await checkRestriction();return;}loadPosts();});el.append(head,body,toolbar,commentsBox,form);return el;}
  async function publishPost(e){e.preventDefault();if(!session?.user){toast('Entre com sua conta para publicar.','error');return;}const ta=ui.postForm.querySelector('textarea');const body=ta.value.trim();if(!body)return;const p=social.state.profile;const r=await client.from('italo_resenha_posts').insert({user_id:session.user.id,display_name:p.display_name,avatar_url:p.avatar_url,body});if(r.error){toast(r.error.message,'error');await checkRestriction();return;}ta.value='';if(ui.postCount)ui.postCount.textContent='0';toast('Publicado.','success');loadPosts();}
  async function moderateDeletePost(id,el){if(!confirm('Excluir esta publicação?'))return;const r=await client.rpc('italo_admin_delete_post',{post_id:id,reason_text:null});if(r.error)toast(r.error.message,'error');else{el.remove();toast('Publicação removida.','success');}}

  async function loadInvites(){if(!session?.user){ui.inviteList.innerHTML='<div class="community-state">Entre para ver convites.</div>';return;}const r=await client.from('italo_game_invites').select('id,user_id,display_name,nickname,platform,available_at,game_mode,note,status,created_at').eq('status','open').gte('available_at',new Date(Date.now()-30*60*1000).toISOString()).order('available_at').limit(12);if(r.error){ui.inviteList.innerHTML='<div class="community-state">Não foi possível carregar convites.</div>';return;}await hydrateUsers((r.data||[]).map(x=>x.user_id));ui.inviteList.replaceChildren();if(!r.data?.length){ui.inviteList.innerHTML='<div class="community-state">Nenhum convite aberto agora.</div>';return;}r.data.forEach(v=>{const row=document.createElement('article');row.className='invite-row';const top=document.createElement('div');top.className='chat-message-meta';top.append(userLink(v.user_id,v.display_name));const b=badgeFor(v.user_id);if(b)top.append(b);const n=document.createElement('strong');n.textContent=v.nickname;const meta=document.createElement('div');meta.className='invite-meta';[v.platform,v.game_mode,fmtDate(v.available_at)].forEach(x=>{const s=document.createElement('span');s.textContent=x;meta.append(s);});row.append(top,n,meta);if(v.note){const note=document.createElement('small');note.textContent=v.note;row.append(note);}ui.inviteList.append(row);});}
  async function publishInvite(e){e.preventDefault();if(!session?.user){toast('Entre para criar um convite.','error');return;}const f=new FormData(ui.inviteForm),available=f.get('available_at');if(!available)return;const p=social.state.profile;const r=await client.from('italo_game_invites').insert({user_id:session.user.id,display_name:p.display_name,avatar_url:p.avatar_url,nickname:String(f.get('nickname')||'').trim(),platform:f.get('platform'),game_mode:f.get('game_mode'),available_at:new Date(available).toISOString(),note:String(f.get('note')||'').trim()||null});if(r.error){toast(r.error.message,'error');return;}ui.inviteForm.reset();toast('Convite publicado.','success');loadInvites();}

  async function loadRanking(){if(!session?.user){ui.ranking.innerHTML='<div class="community-state">Entre para visualizar o ranking.</div>';return;}const r=await client.from('italo_ranking').select('user_id,points,updated_at').order('points',{ascending:false}).order('updated_at').limit(20);if(r.error){ui.ranking.innerHTML='<div class="community-state">Não foi possível carregar o ranking.</div>';return;}await hydrateUsers((r.data||[]).map(x=>x.user_id));ui.ranking.replaceChildren();if(!r.data?.length){ui.ranking.innerHTML='<div class="community-state">O ranking ainda não possui pontuações.</div>';return;}r.data.forEach((x,i)=>{const p=profileCache.get(x.user_id);const row=document.createElement('article');row.className='ranking-row';const pos=document.createElement('span');pos.className='ranking-pos';pos.textContent=`${i+1}º`;const img=document.createElement('img');img.src=p?.avatar_url||'assets/avatar.jpg';img.alt='';const name=document.createElement('div');name.className='ranking-name';const a=userLink(x.user_id,p?.display_name||'Jogador');name.append(a);const badge=badgeFor(x.user_id);if(badge)name.append(badge);const u=document.createElement('small');u.textContent=p?.username?'@'+p.username:'';name.append(u);const pts=document.createElement('span');pts.className='ranking-points';pts.textContent=`${x.points} pts`;row.append(pos,img,name,pts);ui.ranking.append(row);});}

  async function loadTopics(){if(!session?.user){ui.topics.innerHTML='<div class="community-state">Entre na sua conta para acessar os tópicos.</div>';return;}const [t,m]=await Promise.all([client.from('italo_topics').select('id,user_id,display_name,title,category,is_open,created_at').eq('is_open',true).order('created_at',{ascending:false}).limit(20),client.from('italo_topic_members').select('topic_id,user_id').eq('user_id',session.user.id).limit(100)]);if(t.error){ui.topics.innerHTML='<div class="community-state">Não foi possível carregar os tópicos.</div>';return;}const joined=new Set((m.data||[]).map(x=>String(x.topic_id)));ui.topics.replaceChildren();if(!t.data?.length){ui.topics.innerHTML='<div class="community-state">Nenhum tópico aberto. Crie o primeiro.</div>';return;}t.data.forEach(x=>{const row=document.createElement('article');row.className='topic-row';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=x.title;const sub=document.createElement('small');sub.textContent=x.category;copy.append(title,sub);const btn=document.createElement('button');btn.className='social-btn secondary';btn.type='button';btn.textContent=joined.has(String(x.id))?'Sair':'Entrar';btn.addEventListener('click',async()=>{const r=joined.has(String(x.id))?await client.from('italo_topic_members').delete().eq('topic_id',x.id).eq('user_id',session.user.id):await client.from('italo_topic_members').insert({topic_id:x.id,user_id:session.user.id});if(r.error)toast(r.error.message,'error');else loadTopics();});row.append(copy,btn);ui.topics.append(row);});}
  async function createTopic(){if(!session?.user){toast('Entre para criar um tópico.','error');return;}const title=prompt('Nome do tópico:')?.trim();if(!title)return;if(title.length<3||title.length>100){toast('Use entre 3 e 100 caracteres.','error');return;}const p=social.state.profile;const r=await client.from('italo_topics').insert({user_id:session.user.id,display_name:p.display_name,title,category:'Comunidade',is_open:true}).select('id').single();if(r.error){toast(r.error.message,'error');return;}await client.from('italo_topic_members').insert({topic_id:r.data.id,user_id:session.user.id});toast('Tópico criado.','success');loadTopics();}

  function startRealtime(){channel?.unsubscribe?.();if(!session?.user)return;channel=client.channel('italo-community-launch').on('postgres_changes',{event:'INSERT',schema:'public',table:'italo_messages'},async payload=>{const row=payload.new;if(!row?.id||messageIds.has(String(row.id)))return;await hydrateUsers([row.user_id]);messageIds.add(String(row.id));ui.messages.append(makeMessage(row));ui.messages.scrollTop=ui.messages.scrollHeight;}).on('postgres_changes',{event:'*',schema:'public',table:'italo_message_restrictions',filter:`user_id=eq.${session.user.id}`},()=>checkRestriction()).on('postgres_changes',{event:'*',schema:'public',table:'italo_ranking'},()=>loadRanking()).subscribe();}
  async function boot(){session=social.state.session;client=social.client;if(!session?.user){signedOutChat();await Promise.all([loadPosts(),loadInvites(),loadRanking(),loadTopics()]);return;}await hydrateUsers([session.user.id]);await Promise.all([loadMessages(true),checkRestriction(),loadPosts(),loadInvites(),loadRanking(),loadTopics()]);startRealtime();}
  function bind(){ui.older?.addEventListener('click',loadOlder);ui.form?.addEventListener('submit',sendMessage);ui.postForm?.addEventListener('submit',publishPost);ui.postForm?.querySelector('textarea')?.addEventListener('input',e=>{if(ui.postCount)ui.postCount.textContent=String(e.target.value.length);});ui.inviteForm?.addEventListener('submit',publishInvite);ui.createTopic?.addEventListener('click',createTopic);}
  function init(s){social=s;bind();boot();}
  document.addEventListener('italo:social-ready',e=>init(e.detail),{once:true});if(window.ITALO_SOCIAL)init(window.ITALO_SOCIAL);
})();
