(() => {
  const client=window.ITALO_SUPABASE;if(!client)return;
  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let session=null,courses=[],favoriteSet=new Set();
  const stateEl=$('[data-course-state]'),catalog=$('[data-course-catalog]'),search=$('[data-course-search]'),filter=$('[data-course-filter]'),recent=$('[data-course-recent]');
  const detail=$('[data-course-detail]');
  const setState=(text,kind='')=>{if(!stateEl)return;stateEl.textContent=text;stateEl.dataset.state=kind;stateEl.hidden=!text;};
  const esc=v=>String(v||'').toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(d)};
  const toast=(m,k='info')=>window.ITALO_SOCIAL?.toast?.(m,k)||alert(m);

  async function getSession(){const r=await client.auth.getSession();session=r.data.session||null;return session;}
  async function loadFavorites(){favoriteSet.clear();if(!session?.user)return;const r=await client.from('italo_course_favorites').select('course_slug').eq('user_id',session.user.id);if(!r.error)(r.data||[]).forEach(x=>favoriteSet.add(x.course_slug));}
  async function toggleFavorite(slug,button){if(!session?.user){if(window.ITALO_SOCIAL?.signIn)return window.ITALO_SOCIAL.signIn();toast('Entre na comunidade para salvar favoritos.');return;}button.disabled=true;let r;if(favoriteSet.has(slug)){r=await client.from('italo_course_favorites').delete().eq('user_id',session.user.id).eq('course_slug',slug);if(!r.error)favoriteSet.delete(slug);}else{r=await client.from('italo_course_favorites').insert({user_id:session.user.id,course_slug:slug});if(!r.error)favoriteSet.add(slug);}button.disabled=false;if(r.error){toast('Não foi possível atualizar o favorito.','error');return;}renderCatalog();syncDetailFavorite();}
  function card(course){const el=document.createElement('article');el.className='academy-card';const media=document.createElement('div');media.className='academy-card-media';const img=document.createElement('img');img.src=course.cover_url||'assets/curso-domine-o-jogo.svg';img.alt=`Capa do curso ${course.title}`;img.loading='lazy';const chip=document.createElement('span');chip.className='academy-card-chip';chip.textContent='Disponível agora';media.append(img,chip);const body=document.createElement('div');body.className='academy-card-body';const meta=document.createElement('div');meta.className='academy-meta';const cat=document.createElement('span');cat.textContent=course.category;meta.append(cat);const h=document.createElement('h3');h.textContent=course.title;const p=document.createElement('p');p.textContent=course.summary;const actions=document.createElement('div');actions.className='academy-card-actions';const details=document.createElement('a');details.className='academy-btn primary';details.href=`curso-detalhe.html?slug=${encodeURIComponent(course.slug)}`;details.textContent='Ver detalhes →';const fav=document.createElement('button');fav.type='button';fav.className='academy-btn secondary academy-fav'+(favoriteSet.has(course.slug)?' is-favorite':'');fav.setAttribute('aria-label',favoriteSet.has(course.slug)?'Remover dos favoritos':'Adicionar aos favoritos');fav.textContent=favoriteSet.has(course.slug)?'★':'☆';fav.addEventListener('click',()=>toggleFavorite(course.slug,fav));actions.append(details,fav);body.append(meta,h,p,actions);el.append(media,body);return el;}
  function renderCatalog(){if(!catalog)return;const term=esc(search?.value),category=filter?.value||'all';const visible=courses.filter(c=>(!term||esc(c.title+' '+c.summary+' '+c.category).includes(term))&&(category==='all'||c.category===category));catalog.replaceChildren();if(!visible.length){setState('Nenhum curso corresponde a este filtro.','empty');return;}setState(`${visible.length} curso${visible.length===1?'':'s'} disponível${visible.length===1?'':'eis'}.`,'success');visible.forEach(c=>catalog.append(card(c)));}
  function fillFilters(){if(!filter)return;const current=filter.value;filter.innerHTML='<option value="all">Todas as categorias</option>';[...new Set(courses.map(c=>c.category))].sort().forEach(category=>{const o=document.createElement('option');o.value=category;o.textContent=category;filter.append(o)});if([...filter.options].some(o=>o.value===current))filter.value=current;}
  async function renderRecent(){if(!recent||!session?.user)return;const r=await client.from('italo_course_history').select('course_slug,last_opened_at').eq('user_id',session.user.id).order('last_opened_at',{ascending:false}).limit(3);recent.replaceChildren();if(r.error||!r.data?.length){recent.closest('.academy-recent')?.setAttribute('hidden','');return;}recent.closest('.academy-recent')?.removeAttribute('hidden');r.data.forEach(item=>{const c=courses.find(x=>x.slug===item.course_slug);if(!c)return;const a=document.createElement('a');a.className='academy-recent-item';a.href=`curso-detalhe.html?slug=${encodeURIComponent(c.slug)}`;const b=document.createElement('strong');b.textContent=c.title;const s=document.createElement('small');s.textContent=`Visto em ${fmt(item.last_opened_at)}`;a.append(b,s);recent.append(a);});}
  async function initCatalog(){if(!catalog)return;setState('Carregando cursos…','loading');await getSession();const [r]=await Promise.all([client.from('italo_courses').select('slug,title,summary,category,cover_url,external_url,sort_order').eq('is_active',true).order('sort_order')]);if(r.error){setState('Não foi possível carregar os cursos agora.','error');return;}courses=r.data||[];await loadFavorites();fillFilters();renderCatalog();renderRecent();search?.addEventListener('input',renderCatalog);filter?.addEventListener('change',renderCatalog);}
  async function syncDetailFavorite(){const btn=$('[data-detail-favorite]');if(!btn)return;const slug=btn.dataset.slug;btn.textContent=favoriteSet.has(slug)?'★ Favorito':'☆ Favoritar';btn.classList.toggle('is-favorite',favoriteSet.has(slug));}
  async function initDetail(){if(!detail)return;const params=new URLSearchParams(location.search);const slug=params.get('slug')||detail.dataset.courseDetail||'como-jogar-bem';detail.dataset.loading='true';await getSession();const [courseR,lessonsR]=await Promise.all([client.from('italo_courses').select('slug,title,summary,category,cover_url,external_url').eq('slug',slug).maybeSingle(),client.from('italo_lessons').select('id,title,lesson_order,content_url').eq('course_slug',slug).eq('is_published',true).order('lesson_order')]);if(courseR.error||!courseR.data){detail.innerHTML='<div class="academy-state" data-state="error">Curso não encontrado.</div>';return;}const c=courseR.data;await loadFavorites();document.title=`${c.title} | Ítalo Football`;const title=$('[data-detail-title]'),summary=$('[data-detail-summary]'),cat=$('[data-detail-category]'),cover=$('[data-detail-cover]'),checkout=$('[data-detail-checkout]'),fav=$('[data-detail-favorite]');if(title)title.textContent=c.title;if(summary)summary.textContent=c.summary;if(cat)cat.textContent=c.category;if(cover){cover.src=c.cover_url||'assets/curso-domine-o-jogo.svg';cover.alt=`Capa do curso ${c.title}`;}if(checkout){checkout.href=c.external_url||'#';checkout.hidden=!c.external_url;}if(fav){fav.dataset.slug=c.slug;fav.addEventListener('click',()=>toggleFavorite(c.slug,fav));syncDetailFavorite();}
    const lessonsHost=$('[data-lessons]'),lessonSection=$('[data-lessons-section]');const lessons=lessonsR.error?[]:(lessonsR.data||[]);if(lessons.length&&lessonsHost){lessonSection?.removeAttribute('hidden');lessonsHost.replaceChildren();lessons.forEach(l=>{const row=document.createElement(l.content_url?'a':'div');row.className='academy-lesson';if(l.content_url){row.href=l.content_url;row.target='_blank';row.rel='noopener noreferrer';}const name=document.createElement('strong');name.textContent=`${l.lesson_order}. ${l.title}`;const st=document.createElement('small');st.textContent=l.content_url?'Abrir aula':'Conteúdo indisponível';row.append(name,st);lessonsHost.append(row);});}else lessonSection?.setAttribute('hidden','');
    if(session?.user){await client.from('italo_course_history').upsert({user_id:session.user.id,course_slug:c.slug,last_opened_at:new Date().toISOString()},{onConflict:'user_id,course_slug'});}detail.dataset.loading='false';}
  initCatalog();initDetail();
})();
