(() => {
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  let social=null,client=null,session=null,all=[],filter='all',channel=null;
  const grid=$('[data-tournament-grid]'),listView=$('[data-tournament-list-view]'),detail=$('[data-tournament-detail]');
  const toast=(m,k='info')=>social?.toast?.(m,k);
  const dt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(d)};
  const statusLabel={open:'Inscrições abertas',scheduled:'Próximo',in_progress:'Em andamento',finished:'Finalizado',cancelled:'Cancelado',draft:'Rascunho'};
  function friendly(error,fallback='Não foi possível concluir esta ação.'){
    const msg=String(error?.message||error?.details||'');
    if(/já está inscrito/i.test(msg))return 'Você já está inscrito neste torneio.';
    if(/limite|lotad/i.test(msg))return 'Este torneio já atingiu o limite de participantes.';
    if(/prazo|inscrições.*abertas/i.test(msg))return 'As inscrições deste torneio não estão disponíveis.';
    if(/removida pela administração/i.test(msg))return 'Sua participação foi removida pela administração e não pode ser refeita.';
    if(/permission|permiss|policy|rls/i.test(msg))return 'Você não possui permissão para realizar esta ação.';
    return fallback;
  }
  function card(t){
    const a=document.createElement('article');a.className='t-card';const cover=document.createElement('div');cover.className='t-card-cover';
    if(t.cover_url){const img=document.createElement('img');img.src=t.cover_url;img.alt=`Capa do torneio ${t.name}`;img.loading='lazy';img.decoding='async';img.onerror=()=>{cover.replaceChildren();const icon=document.createElement('span');icon.textContent='🏆';cover.append(icon)};cover.append(img)}else{const icon=document.createElement('span');icon.textContent='🏆';cover.append(icon)}
    const copy=document.createElement('div');copy.className='t-card-copy';const st=document.createElement('span');st.className='t-card-status '+t.status;st.textContent=statusLabel[t.status]||t.status;const h=document.createElement('h3');h.textContent=t.name;const p=document.createElement('p');p.textContent=t.description||'Torneio da comunidade Ítalo Football.';const meta=document.createElement('div');meta.className='t-card-meta';[['📅',dt(t.starts_at)],['🎮',t.platform],['👥',`${t.participant_count||0}/${t.max_participants}`]].forEach(([i,x])=>{const s=document.createElement('span');s.textContent=`${i} ${x}`;meta.append(s)});const act=document.createElement('div');act.className='t-card-actions';const link=document.createElement('a');link.className='social-btn primary';link.href=`torneios.html?t=${encodeURIComponent(t.slug)}`;link.textContent='Visualizar';act.append(link);copy.append(st,h,p,meta,act);a.append(cover,copy);return a;
  }
  async function load(){
    grid.innerHTML='<div class="t-loading">Carregando torneios…</div>';
    const t=await client.from('italo_tournaments').select('id,slug,name,description,cover_url,starts_at,registration_deadline,max_participants,participant_count,rules,platform,format,tournament_type,status,prize,champion_user_id,created_at').neq('status','draft').order('starts_at',{ascending:true});
    if(t.error){grid.innerHTML='<div class="t-empty">Não foi possível carregar os torneios.</div>';return}all=t.data||[];renderList();
  }
  function renderList(){grid.replaceChildren();const rows=filter==='all'?all:all.filter(x=>x.status===filter);if(!rows.length){grid.innerHTML='<div class="t-empty">Nenhum torneio nesta categoria.</div>';return}rows.forEach(x=>grid.append(card(x)))}
  async function profileMap(ids){ids=[...new Set(ids.filter(Boolean))];if(!ids.length)return new Map();const r=await client.from('italo_profiles').select('user_id,display_name,username,avatar_url,role_badge,is_channel_member').in('user_id',ids);return new Map((r.data||[]).map(x=>[x.user_id,x]))}
  function badge(p){if(p?.role_badge==='owner'){const b=document.createElement('span');b.className='role-badge owner';b.textContent='OWNER';return b}if(p?.role_badge==='admin'){const b=document.createElement('span');b.className='role-badge admin';b.textContent='ADM';return b}if(p?.is_channel_member){const b=document.createElement('span');b.className='member-exclusive-badge';b.textContent='★ Membro Exclusivo';return b}return null}
  async function renderDetail(slug,id=null){
    listView.hidden=true;detail.hidden=false;detail.innerHTML='<div class="t-loading">Carregando torneio…</div>';let tq=client.from('italo_tournaments').select('*');tq=id?tq.eq('id',id):tq.eq('slug',slug);const tr=await tq.maybeSingle();if(tr.error||!tr.data){detail.innerHTML='<div class="t-empty">Torneio não encontrado.</div>';return}const t=tr.data;
    let participants=[],matches=[];
    if(session?.user){const [p,m]=await Promise.all([client.from('italo_tournament_participants').select('*').eq('tournament_id',t.id).order('joined_at'),client.from('italo_tournament_matches').select('*').eq('tournament_id',t.id).order('round_no').order('match_no')]);participants=p.data||[];matches=m.data||[]}
    const ids=[...participants.map(x=>x.user_id),...matches.flatMap(x=>[x.participant1_id,x.participant2_id,x.winner_id]),t.champion_user_id];const profiles=await profileMap(ids);detail.replaceChildren();
    const back=document.createElement('a');back.href='torneios.html';back.className='social-btn secondary t-back';back.textContent='← Todos os torneios';detail.append(back);
    const hero=document.createElement('section');hero.className='t-detail-hero';const st=document.createElement('span');st.className=`t-card-status ${t.status}`;st.textContent=statusLabel[t.status]||t.status;const h=document.createElement('h2');h.textContent=t.name;const desc=document.createElement('p');desc.textContent=t.description||'';hero.append(st,h,desc);
    const actions=document.createElement('div');actions.className='t-detail-actions';if(session?.user){const mine=participants.find(x=>x.user_id===session.user.id);if(t.status==='open'&&Date.now()<=new Date(t.registration_deadline).getTime()&&mine?.status!=='registered'){const join=document.createElement('button');join.className='social-btn primary';join.type='button';join.textContent='Inscrever-se';join.addEventListener('click',()=>joinTournament(t.id,join));actions.append(join)}if(mine?.status==='registered'&&['open','scheduled'].includes(t.status)){const leave=document.createElement('button');leave.className='social-btn secondary';leave.type='button';leave.textContent='Cancelar inscrição';leave.addEventListener('click',()=>leaveTournament(t.id,leave));actions.append(leave)}}else{const login=document.createElement('a');login.href='perfil.html';login.className='social-btn primary';login.textContent='Entrar para participar';actions.append(login)}if(['admin','owner'].includes(social?.state?.access?.role)){const adm=document.createElement('a');adm.href='admin.html#torneios';adm.className='social-btn secondary';adm.textContent='Gerenciar no ADM';actions.append(adm)}hero.append(actions);
    const info=document.createElement('div');info.className='t-detail-info';[['Data',dt(t.starts_at)],['Plataforma',t.platform],['Participantes',`${t.participant_count||0}/${t.max_participants}`],['Formato','Mata-mata']].forEach(([k,v])=>{const x=document.createElement('div');x.className='t-stat';const small=document.createElement('small'),strong=document.createElement('strong');small.textContent=k;strong.textContent=v;x.append(small,strong);info.append(x)});hero.append(info);detail.append(hero);
    if(t.champion_user_id){const p=profiles.get(t.champion_user_id),champ=document.createElement('div');champ.className='t-champion';const ico=document.createElement('b');ico.textContent='🏆';const cp=document.createElement('div'),lab=document.createElement('small'),name=document.createElement('strong');lab.textContent='CAMPEÃO';name.textContent=p?.display_name||'Campeão';cp.append(lab,name);champ.append(ico,cp);detail.append(champ)}
    const part=section('Participantes'),plist=document.createElement('div');plist.className='participant-list';if(!session?.user){plist.innerHTML='<div class="t-empty">Entre para visualizar a lista de participantes.</div>'}else{const visible=participants.filter(x=>x.status!=='removed');if(!visible.length)plist.innerHTML='<div class="t-empty">Nenhum participante inscrito.</div>';visible.forEach(x=>{const p=profiles.get(x.user_id),row=document.createElement('article');row.className='participant';const img=document.createElement('img');img.src=p?.avatar_url||'assets/avatar.jpg';img.alt='';img.loading='lazy';img.decoding='async';const cp=document.createElement('div');cp.className='participant-copy';const a=document.createElement('a');a.href=p?.username?`perfil.html?u=${encodeURIComponent(p.username)}`:'perfil.html';a.textContent=p?.display_name||'Jogador';cp.append(a);const b=badge(p);if(b)cp.append(b);const s=document.createElement('small');s.textContent=p?.username?`@${p.username} • ${x.status}`:x.status;cp.append(s);row.append(img,cp);plist.append(row)})}part.querySelector('.t-section-body').append(plist);detail.append(part);
    const br=section('Chaveamento'),body=br.querySelector('.t-section-body');if(!session?.user)body.innerHTML='<div class="t-empty">Entre para visualizar o chaveamento.</div>';else if(!matches.length)body.innerHTML='<div class="t-empty">O chaveamento será exibido quando o torneio começar.</div>';else body.append(makeBracket(matches,profiles));detail.append(br);
    if(t.rules){const rules=section('Regras'),r=document.createElement('div');r.className='t-rules';r.textContent=t.rules;rules.querySelector('.t-section-body').append(r);detail.append(rules)}
  }
  function section(title){const s=document.createElement('section');s.className='t-section';const head=document.createElement('header');head.className='t-section-head';const h=document.createElement('h3');h.textContent=title;head.append(h);const body=document.createElement('div');body.className='t-section-body';s.append(head,body);return s}
  function makeBracket(matches,profiles){const wrap=document.createElement('div');wrap.className='bracket-wrap';const br=document.createElement('div');br.className='bracket';const rounds=[...new Set(matches.map(x=>x.round_no))];rounds.forEach(r=>{const col=document.createElement('div');col.className='bracket-round';const h=document.createElement('h4');h.textContent=r===rounds.length?'Final':`Rodada ${r}`;col.append(h);matches.filter(x=>x.round_no===r).forEach(m=>{const box=document.createElement('article');box.className='match';[[m.participant1_id,m.score1],[m.participant2_id,m.score2]].forEach(([id,score])=>{const p=profiles.get(id),row=document.createElement('div');row.className='match-player'+(m.winner_id===id?' winner':'');const n=document.createElement('span');n.textContent=id?(p?.display_name||'Jogador'):'A definir';const sc=document.createElement('b');sc.textContent=score==null?'—':String(score);row.append(n,sc);box.append(row)});col.append(box)});br.append(col)});wrap.append(br);return wrap}
  async function joinTournament(id,b){if(b.disabled)return;b.disabled=true;b.setAttribute('aria-busy','true');const r=await client.rpc('italo_join_tournament',{tournament_id:id});b.disabled=false;b.removeAttribute('aria-busy');if(r.error){toast(friendly(r.error,'Não foi possível concluir a inscrição.'),'error');return}toast('Inscrição confirmada.','success');renderDetail(null,id)}
  async function leaveTournament(id,b){if(!confirm('Cancelar sua inscrição neste torneio?'))return;if(b.disabled)return;b.disabled=true;const r=await client.rpc('italo_leave_tournament',{tournament_id:id});b.disabled=false;if(r.error){toast(friendly(r.error,'Não foi possível cancelar a inscrição.'),'error');return}toast('Inscrição cancelada.','success');renderDetail(null,id)}
  function currentDetail(){const params=new URLSearchParams(location.search);return{slug:params.get('t'),id:params.get('id')}}
  function startRealtime(){if(!session?.user)return;channel=client.channel('italo-tournaments-ui').on('postgres_changes',{event:'*',schema:'public',table:'italo_tournaments'},()=>{const x=currentDetail();if(x.slug||x.id)renderDetail(x.slug,x.id);else load()}).on('postgres_changes',{event:'*',schema:'public',table:'italo_tournament_participants'},()=>{const x=currentDetail();if(x.slug||x.id)renderDetail(x.slug,x.id);else load()}).on('postgres_changes',{event:'*',schema:'public',table:'italo_tournament_matches'},()=>{const x=currentDetail();if(x.slug||x.id)renderDetail(x.slug,x.id)}).subscribe()}
  function bind(){$$('[data-tournament-filter] button').forEach(b=>b.addEventListener('click',()=>{$$('[data-tournament-filter] button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderList()}))}
  async function init(s){social=s;client=s.client;session=s.state.session;bind();const x=currentDetail();if(x.slug||x.id)await renderDetail(x.slug,x.id);else await load();startRealtime()}
  document.addEventListener('italo:social-ready',e=>init(e.detail),{once:true});if(window.ITALO_SOCIAL)init(window.ITALO_SOCIAL);
})();